version: 0.2

env:
  variables:
    version: "0.0.2-SNAPSHOT"
phases:
  install:
    runtime-versions:
      java: "openjdk8"
    commands:
      - yum install -y java-1.8.0-openjdk
      - yum install -y tar
      - yum install -y wget
      - aws --version
      - java -version
#      - pwd
      - wget -P /tmp https://mirror.bit.edu.cn/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
      - tar zxf /tmp/apache-maven-3.6.3-bin.tar.gz
      - ls /tmp -al
  #      - ls /tmp
#      - export PATH=/opt/apache-maven-3.6.3/bin:$PATH
  pre_build:
    commands:
      - mvn clean && mvn compile
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - mvn package
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - aws ecr batch-delete-image --repository-name $IMAGE_REPO_NAME --image-ids imageTag=$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG